"""split_soul_pillars

Revision ID: 3b9d86723493
Revises: 3b9cab9eeee1
Create Date: 2026-02-05 21:16:47.427023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import json

# revision identifiers, used by Alembic.
revision: str = '3b9d86723493'
down_revision: Union[str, Sequence[str], None] = '3b9cab9eeee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and migrate data."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soul_pillars',
    sa.Column('soul_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routines', sa.JSON(), nullable=True),
    sa.Column('identity_pillar', sa.JSON(), nullable=True),
    sa.Column('aesthetic_pillar', sa.JSON(), nullable=True),
    sa.Column('interaction_engine', sa.JSON(), nullable=True),
    sa.Column('llm_instruction_override', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['soul_id'], ['souls.soul_id'], ),
    sa.PrimaryKeyConstraint('soul_id')
    )
    op.create_table('soul_states',
    sa.Column('soul_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_location_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('anxiety_level', sa.Integer(), nullable=False),
    sa.Column('performance_mode', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['soul_id'], ['souls.soul_id'], ),
    sa.PrimaryKeyConstraint('soul_id')
    )

    # --- DATA MIGRATION ---
    connection = op.get_bind()
    souls = connection.execute(sa.text("SELECT soul_id, routines, identity_pillar, aesthetic_pillar, interaction_engine, llm_instruction_override, meta_data, personality, spawn_location FROM souls")).fetchall()
    
    for s in souls:
        # Move to soul_pillars
        connection.execute(
            sa.text("INSERT INTO soul_pillars (soul_id, routines, identity_pillar, aesthetic_pillar, interaction_engine, llm_instruction_override, meta_data, personality) VALUES (:id, :rout, :idp, :aep, :ite, :llm, :met, :per)"),
            {
                "id": s[0], 
                "rout": json.dumps(s[1]), 
                "idp": json.dumps(s[2]), 
                "aep": json.dumps(s[3]), 
                "ite": json.dumps(s[4]), 
                "llm": json.dumps(s[5]), 
                "met": json.dumps(s[6]), 
                "per": s[7]
            }
        )
        # Move to soul_states
        connection.execute(
            sa.text("INSERT INTO soul_states (soul_id, current_location_id, energy, mood, anxiety_level, performance_mode, last_updated) VALUES (:id, :loc, 100, 'neutral', 0, 100, NOW())"),
            {
                "id": s[0], 
                "loc": s[8]
            }
        )

    op.drop_column('souls', 'routines')
    op.drop_column('souls', 'interaction_engine')
    op.drop_column('souls', 'spawn_location')
    op.drop_column('souls', 'llm_instruction_override')
    op.drop_column('souls', 'personality')
    op.drop_column('souls', 'meta_data')
    op.drop_column('souls', 'aesthetic_pillar')
    op.drop_column('souls', 'identity_pillar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema and restore data."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souls', sa.Column('identity_pillar', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('aesthetic_pillar', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('personality', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('llm_instruction_override', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('spawn_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('interaction_engine', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('souls', sa.Column('routines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # --- DATA RESTORATION ---
    connection = op.get_bind()
    pillars = connection.execute(sa.text("SELECT soul_id, routines, identity_pillar, aesthetic_pillar, interaction_engine, llm_instruction_override, meta_data, personality FROM soul_pillars")).fetchall()
    states = connection.execute(sa.text("SELECT soul_id, current_location_id FROM soul_states")).fetchall()
    
    state_map = {s[0]: s[1] for s in states}
    
    for p in pillars:
        connection.execute(
            sa.text("UPDATE souls SET routines=:rout, identity_pillar=:idp, aesthetic_pillar=:aep, interaction_engine=:ite, llm_instruction_override=:llm, meta_data=:met, personality=:per, spawn_location=:loc WHERE soul_id=:id"),
            {
                "id": p[0], 
                "rout": json.dumps(p[1]), 
                "idp": json.dumps(p[2]), 
                "aep": json.dumps(p[3]), 
                "ite": json.dumps(p[4]), 
                "llm": json.dumps(p[5]), 
                "met": json.dumps(p[6]), 
                "per": p[7],
                "loc": state_map.get(p[0], 'soul_plaza')
            }
        )

    op.drop_table('soul_states')
    op.drop_table('soul_pillars')
    # ### end Alembic commands ###
