"""Add index to conversation

Revision ID: c3610a17d531
Revises: 3b9d86723493
Create Date: 2026-02-09 12:57:05.899492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3610a17d531'
down_revision: Union[str, Sequence[str], None] = '3b9d86723493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversation_user_soul_created', 'conversations', ['user_id', 'soul_id', 'created_at'], unique=False)
    op.add_column('soul_pillars', sa.Column('background', sa.Text(), nullable=True))
    op.alter_column('soul_pillars', 'routines',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('soul_pillars', 'personality',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('soul_pillars', 'identity_pillar',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('soul_pillars', 'aesthetic_pillar',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('soul_pillars', 'interaction_engine',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('soul_pillars', 'llm_instruction_override',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('soul_pillars', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soul_pillars', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('soul_pillars', 'llm_instruction_override',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('soul_pillars', 'interaction_engine',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('soul_pillars', 'aesthetic_pillar',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('soul_pillars', 'identity_pillar',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('soul_pillars', 'personality',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('soul_pillars', 'routines',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('soul_pillars', 'background')
    op.drop_index('ix_conversation_user_soul_created', table_name='conversations')
    # ### end Alembic commands ###
